---
# tasks file for firewall
- name: load default variables
  include_vars:
    file: default.yml

- name: load os-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - default.yml

- name: install software
  package:
    name: firewalld

- name: start and enable software
  service:
    name: firewalld
    state: started
    enabled: true

- name: open tcp ports
  firewalld:
    service: "{{ item.service }}"
    permanent: true
    state: enabled
  with_items:
    - "{{ firewall_services }}"
