---
# tasks file for firewall
- name: remove conflicting software
  package:
    name: "{{ firewall_packages['conflicting'][ansible_distribution]
          | default[firewall_packages['conflicting']['default']) }}"
    state: absent
  when:
    - firewall_packages.conflicting is defined

- name: install required software
  package:
    name: "{{ firewall_packages['required'][ansible_distribution]
          | default[firewall_packages['required']['default']) }}"
    state: "{{ firewall_package_state }}"
  when:
    - firewall_packages.required is defined

- name: open ports (ufw)
  ufw:
    rule: "{{ item.rule | default('allow') }}"
    port: "{{ item.name }}"
    proto: "{{ item.protocol | default('tcp') }}"
  with_items:
    - "{{ firewall_services }}"
  when:
    - firewall_services is defined
    - firewall_service == "ufw"
    - ansible_virtualization_type != "docker"
  loop_control:
    label: "{{ item.name }}"

- name: open ports (firewalld-port)
  firewalld:
    port: "{{ item.name }}/{{ item.protocol | default('tcp') }}"
    permanent: true
    state: enabled
  with_items:
    - "{{ firewall_services }}"
  when:
    - firewall_services is defined
    - firewall_service == "firewalld"
    - ansible_virtualization_type != "docker"
    - item.name is number
  loop_control:
    label: "{{ item.name }}"

- name: open ports (firewalld-service)
  firewalld:
    service: "{{ item.name }}"
    permanent: true
    state: enabled
  with_items:
    - "{{ firewall_services }}"
  when:
    - firewall_services is defined
    - firewall_service == "firewalld"
    - ansible_virtualization_type != "docker"
    - item.name is not number
  loop_control:
    label: "{{ item.name }}"

- name: enable ufw
  ufw:
    state: enabled
  when:
    - firewall_service[ansible_distribution]
      | default[firewall_service['default'] ) == "ufw"
    - ansible_virtualization_type != "docker"

- name: configure iptables
  template:
    src: iptables.j2
    dest: "{{ firewall_iptables_rulefile[ansible_distribution]
          | default[firewall_iptables_rulefile['default'] }}"
    validate: "iptables-restore --test %s"
  when:
    - ansible_virtualization_type != "docker"
    - firewall_services is defined
    - firewall_service[ansible_distribution]
      | default[firewall_service['default'] ) == "iptables"
  loop_control:
    label: "{{ item.name }}"
  notify:
    - reload firewall

- name: start and enable software
  service:
    name: "{{ firewall_service[ansible_distribution]
          | default[firewall_service['default'] }}"
    state: started
    enabled: true
  when:
    - ansible_virtualization_type != "docker"
    - firewall_service is defined
