---
# tasks file for firewall
- name: load default variables
  include_vars:
    file: default.yml

- name: load os-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - default.yml

- name: remove conflicting software
  package:
    name: "{{ item.name }}"
    state: absent
  with_items:
    - "{{ firewall_conflicting_packages }}"
  when:
    - "{{ firewall_conflicting_packages}}"

- name: install software
  package:
    name: "{{ item.name }}"
    state: present
  with_items:
    - "{{ firewall_required_package }}"
  when:
    - "{{ firewall_required_package }}"

- name: start and enable software
  service:
    name: "{{ firewall_service }}"
    state: started
    enabled: true
  when:
    - ansible_virtualization_type != "docker"
    - "{{ firewall_service }}"

- name: open tcp ports (ufw)
  ufw:
    rule: "{{ item.state }}"
    port: "{{ item.name }}"
    proto: "{{ item.protocol }}"
  with_items:
    - "{{ firewall_services }}"
  when:
    - "{{ firewall_services }}"
    - firewall_service == "uwf"
    - ansible_virtualization_type != "docker"

- name: open tcp ports (firewalld)
  firewalld:
    service: "{{ item.name }}"
    permanent: true
    state: "{% if item.state == 'allow' %}enabled{% else %}disabled{% endif %}"
  with_items:
    - "{{ firewall_services }}"
    - firewall_service == "firewalld"
    - ansible_virtualization_type != "docker"
