---
# handlers file for firewall
- name: reload firewall
  service:
    name: "{{ firewall_service }}"
    state: reloaded
  when:
    - ansible_connection != "docker"

- name: reload firewalld
  command: firewall-cmd --reload
