---
# handlers file for firewall
- name: reload firewall
  service:
    name: "{{ firewall_service[ansible_distribution]
          | default[firewall_service['default'] }}"
    state: reloaded
  when:
    - ansible_virtualization_type != "docker"
