---
# handlers file for firewall

- name: reload firewall
  service:
    name: "{{ firewall_service }}"
    state: reloaded
  when:
    - ansible_connection != "docker"
    - not ansible_check_mode | bool

- name: reload firewalld
  command: firewall-cmd --reload
